#########################################################
#  Macro file for filtering scoring mesh
#  based on particle type.
#  Scoring meshes are defined for: e-, protons, neutrons, gammas, 
#  alphas, and muons
#########################################################

#Defining the scoring meshes
/score/create/boxMesh boxMesh
/score/mesh/boxSize 15. 20. 5. m
/score/mesh/nBin 50 50 50


/score/quantity/energyDeposit eDepElectron
/score/filter/particle electronEnergy e-
/score/quantity/doseDeposit dDepElectron
/score/filter/particle electronDose e-
/score/quantity/cellFlux fluxElectron
/score/filter/particle electronFlux e-

/score/quantity/energyDeposit eDepProton
/score/filter/particle protonEnergy proton
/score/quantity/doseDeposit dDepProton
/score/filter/particle protonDose proton
/score/quantity/cellFlux fluxProton
/score/filter/particle protonFlux proton

/score/quantity/energyDeposit eDepNeutron
/score/filter/particle neutronEnergy neutron
/score/quantity/doseDeposit dDepNeutron
/score/filter/particle neutronDose neutron
/score/quantity/cellFlux fluxNeutron
/score/filter/particle neutronFlux neutron

/score/quantity/energyDeposit eDepGamma
/score/filter/particle gammaEnergy gamma
/score/quantity/doseDeposit dDepGamma
/score/filter/particle gammaDose gamma
/score/quantity/cellFlux fluxGamma
/score/filter/particle gammaFlux gamma

/score/quantity/energyDeposit eDepAlpha
/score/filter/particle alphaEnergy alpha
/score/quantity/doseDeposit dDepAlpha
/score/filter/particle alphaDose alpha
/score/quantity/cellFlux fluxAlpha
/score/filter/particle alphaFlux alpha

/score/quantity/energyDeposit eDepMuonPlus
/score/filter/particle muonPlusEnergy mu+
/score/quantity/doseDeposit dDepMuonPlus
/score/filter/particle muonPlusDose mu+
/score/quantity/cellFlux fluxMuonPlus
/score/filter/particle MuonPlusFlux mu+

/score/quantity/energyDeposit eDepMuonMinus
/score/filter/particle muonMinusEnergy mu-
/score/quantity/doseDeposit dDepMuonMinus
/score/filter/particle muonMinusDose mu-
/score/quantity/cellFlux fluxMuonMinus
/score/filter/particle MuonMinusFlux mu-

/score/close
/score/list

##Defining beam parameters
/gps/pos/shape Circle
/gps/pos/centre 8.74395 -4.93871 -0.561975 m
/gps/pos/radius 20. um
/gps/pos/sigma_r 0. mm
/gps/particle e-
/gps/pos/type Beam

# the incident surface is in the x-z plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1

/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 0 1 
/gps/ang/type beam1d
/gps/ang/maxtheta 0.370 deg

/gps/ene/type Gauss
/gps/ene/mono 125 GeV
/gps/ene/sigma 2.25 GeV

/run/beamOn 5

#Dump score to files.
/score/dumpQuantityToFile boxMesh eDepElectron filtered_output/eDepElectron.txt
/score/dumpQuantityToFile boxMesh dDepElectron filtered_output/dDepElectron.txt
/score/dumpQuantityToFile boxMesh fluxElectron filtered_output/fluxElectron.txt

/score/dumpQuantityToFile boxMesh eDepProton filtered_output/eDepProton.txt
/score/dumpQuantityToFile boxMesh dDepProton filtered_output/dDepProton.txt
/score/dumpQuantityToFile boxMesh fluxProton filtered_output/fluxProton.txt

/score/dumpQuantityToFile boxMesh eDepNeutron filtered_output/eDepNeutron.txt
/score/dumpQuantityToFile boxMesh dDepNeutron filtered_output/dDepNeutron.txt
/score/dumpQuantityToFile boxMesh fluxNeutron filtered_output/fluxNeutron.txt

/score/dumpQuantityToFile boxMesh eDepGamma filtered_output/eDepGamma.txt
/score/dumpQuantityToFile boxMesh dDepGamma filtered_output/dDepGamma.txt
/score/dumpQuantityToFile boxMesh fluxGamma filtered_output/fluxGamma.txt

/score/dumpQuantityToFile boxMesh eDepAlpha filtered_output/eDepAlpha.txt
/score/dumpQuantityToFile boxMesh dDepAlpha filtered_output/dDepAlpha.txt
/score/dumpQuantityToFile boxMesh fluxAlpha filtered_output/fluxAlpha.txt

/score/dumpQuantityToFile boxMesh eDepMuonPlus filtered_output/eDepMuonPlus.txt
/score/dumpQuantityToFile boxMesh dDepMuonPlus filtered_output/dDepMuonPlus.txt
/score/dumpQuantityToFile boxMesh fluxMuonPlus filtered_output/fluxMuonPlus.txt

/score/dumpQuantityToFile boxMesh eDepMuonMinus filtered_output/eDepMuonMinus.txt
/score/dumpQuantityToFile boxMesh dDepMuonMinus filtered_output/dDepMuonMinus.txt
/score/dumpQuantityToFile boxMesh fluxMuonMinus filtered_output/fluxMuonMinus.txt



















