#Defining Volume and Scorer for Phantom 6
/score/create/cylinderMesh Phantom6Mesh
/score/mesh/cylinderSize 40. 180. cm
/score/mesh/translate/xyz 5.28675 16.5144 -0.0998 m
/score/mesh/nBin 30 30 30

#Defining Scorers
/score/quantity/energyDeposit eDepElectron
/score/filter/particle electronEnergy e-
/score/quantity/doseDeposit dDepElectron
/score/filter/particle electronDose e-

/score/quantity/energyDeposit eDepProton
/score/filter/particle protonEnergy proton
/score/quantity/doseDeposit dDepProton
/score/filter/particle protonDose proton

/score/quantity/energyDeposit eDepNeutron
/score/filter/particle neutronEnergy neutron
/score/quantity/doseDeposit dDepNeutron
/score/filter/particle neutronDose neutron

/score/quantity/energyDeposit eDepGamma
/score/filter/particle gammaEnergy gamma
/score/quantity/doseDeposit dDepGamma
/score/filter/particle gammaDose gamma

/score/quantity/energyDeposit eDepAlpha
/score/filter/particle alphaEnergy alpha
/score/quantity/doseDeposit dDepAlpha
/score/filter/particle alphaDose alpha

/score/quantity/energyDeposit eDepMuonPlus
/score/filter/particle muonPlusEnergy mu+
/score/quantity/doseDeposit dDepMuonPlus
/score/filter/particle muonPlusDose mu+

/score/quantity/energyDeposit eDepMuonMinus
/score/filter/particle muonMinusEnergy mu-
/score/quantity/doseDeposit dDepMuonMinus
/score/filter/particle muonMinusDose mu-

/score/close